# Generated by Django 4.2 on 2023-06-15 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("last_login", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("password", models.TextField(max_length=10)),
                ("q1", models.CharField(default="", max_length=20, null=True)),
                ("q2", models.CharField(default="", max_length=20, null=True)),
                ("q3", models.CharField(default="", max_length=20, null=True)),
                ("q4", models.CharField(default="", max_length=20, null=True)),
                ("q5", models.CharField(default="", max_length=10, null=True)),
                ("q6", models.CharField(default="", max_length=10, null=True)),
                ("q7", models.CharField(default="", max_length=10, null=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("q1", models.CharField(max_length=20)),
                ("q2", models.CharField(max_length=20)),
                ("q3", models.CharField(max_length=20)),
                ("q4", models.CharField(max_length=20)),
                ("q5", models.CharField(max_length=10)),
                ("q6", models.CharField(max_length=10)),
                ("q7", models.CharField(max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.user"
                    ),
                ),
            ],
        ),
    ]
